name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
permissions:
  contents: write
jobs:
  
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
      - run: 
          cd ${{github.workspace}};
          mkdir ./generatedcomics;
          for comic in ./Comics/*;
            do
                for page in $comic/*.png; 
                do
                  echo $page;
                  echo $page > $comic.html;
                  cat $comic.html;
                done
            done
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
  createFile:
          name: Create A File
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2
            - uses: 1arp/create-a-file-action@0.4.5
              with:
                path: 'src'
                isAbsolutePath: false
                file: 'foo.bar'
                content: |
                  Hello
                  World