name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
      - run: for comic in ./Comics/*; 
            do
              touch $comic.html;
                for page in $comic/*.png; 
                do
                  cat $page >> $comic.html;
                done
            done
  createFile:
          name: Create A File
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2
            - uses: 1arp/create-a-file-action@0.4.5
              with:
                path: 'src'
                isAbsolutePath: false
                file: 'foo.bar'
                content: |
                  Hello
                  World